### ISSUE TITLE
Decius Cerasus quest requires clarification

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#106]
Illarion-Content/npc/decius_cerasus_industrius.npc 
Quest 10 - line 268-283
Clarity required for ruby amulet requested following fine smithing expansion. Should be described as 'Golden Ruby Amulet'.

Other NPC requests may have been impacted by the crafting expansion.

**Comment by estralis** [comment]
https://github.com/Illarion-eV/Illarion-Content/commit/1958968083e1cf9f4a35d9c8b0d65d060314a7a2
