### ISSUE TITLE
Map Revision - Stage 1

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#128]
Key tasks:
Topographical revision - Tiling and vegetation / rocks item mapping.
Item mapping for harbour, Noobia (pier / orchard / microbrewery), market (excluding player trade showcase), onion ball.

Dependent on:
No dependencies - Ready to start

**Comment by slightlycomatose** [comment]
#37 Troll's Haven - Stage 1 mapping

**Comment by estralis** [comment]
Shouldn't this go to the map repository?

**Comment by slightlycomatose** [comment]
Pull request 40 on Illarion-Map: Troll's Haven - Stage 1 mapping feedback revisions

**Comment by EviePryler** [comment]
I have merged and checked these map works.  They look good and are approved.

**Comment by slightlycomatose** [comment]
Complete on dev server to go live with next update.
