### ISSUE TITLE
Planting trees does not give proper inform.

### ISSUE THREAD

**Issue by EviePryler** [Illarion-eV/Illarion-Content#134]
While testing planting orange trees I discovered that the fail inform for planting on the wrong soil is not working. I tested and it is the same case for other seedID items. Sadly I lack the knowledge to fix this.    From the Dev server error log

12 Nov 14 03:32:37 Script (err): No matching overload found, candidates:
void inform(Character const*,std::string const&)
void inform(Character const*,std::string const&,std::string const&)
void inform(Character const*,std::string const&,custom [N9Character10informTypeE])
void inform(Character const*,std::string const&,std::string const&,custom [N9Character10informTypeE])
#1 called by: [C]:-1(method inform)
#2 called by: ...re/servers/devserver/scripts/item/id_52_filledbucket.lua:421(upvalue plantTree)
#3 called by: ...re/servers/devserver/scripts/item/id_52_filledbucket.lua:50

**Comment by estralis** [comment]
Various "options" in isTreePlantableHere do not return texts. In such a case, either, no message should be displayed or a default text needs to be returned.
