### ISSUE TITLE
Database: transfer_server does not transfer all necessary data

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#137]

**Comment by vilarion** [comment]
No actionable info.

**Comment by estralis** [comment]
The following needs to be added between line 32 and 33 of the function transfer_server:

"itm_description_german" = "ts_items"."itm_description_german",
"itm_description_english" = "ts_items"."itm_description_english",
"itm_rareness" = "ts_items"."itm_itm_rareness"

I can't do this.

SQL-Fehler:

ERROR:  permission denied for schema illarionserver

**Comment by vilarion** [comment]
Applied the change, but used itm_rareness instead of itm_itm_rareness.
