### ISSUE TITLE
Bug in bridge ambush script

### ISSUE THREAD

**Issue by merung** [Illarion-eV/Illarion-Content#140]
1 Dec 19 10:41:55 Script (err): World::createMonster: Failed to create monster with unknown id 321!

1 Dec 19 10:41:55 Script (err): std::logic_error: 'Usage of invalid Character! Use isValidChar( char ) to check if a Character is still valid.'
#1 called by: [C]:-1(method createMonster)
#2 called by: ...arionserver/scripts/triggerfield/galmair_bridges_660.lua:120(field triggerAmbush)
#3 called by: ...rionserver/scripts/triggerfield/galmair_bridges1_660.lua:38

**Comment by estralis** [comment]
Well, yes, there is no monster 321.

**Comment by EviePryler** [comment]
bug fixed in dev sever with updated monster numbers
