### ISSUE TITLE
Bug removing shards from forged items

### ISSUE THREAD

**Issue by EviePryler** [Illarion-eV/Illarion-Content#146]
Player reported in support issues with removing shards from forged items.  I found this in the error log:

1 Feb 17 18:08:46 Script (err): Exception in SelectionDialog callback: /usr/share/servers/illarionserver/scripts/base/glyphs.lua:287: attempt to index local 'item' (a number value)
#1 called by: /usr/share/servers/illarionserver/scripts/base/glyphs.lua:287(field getWorkingTime)
#2 called by: ...hare/servers/illarionserver/scripts/magic/glyphmagic.lua:292(upvalue startRitualBreakGlyph)
#3 called by: ...hare/servers/illarionserver/scripts/magic/glyphmagic.lua:508

**Comment by NeiaC** [comment]
Sent a pull request for a fix https://github.com/Illarion-eV/Illarion-Content/pull/147
