### ISSUE TITLE
Make portal books craftable

### ISSUE THREAD

**Issue by EviePryler** [Illarion-eV/Illarion-Content#150]
In Gobaith mages could make portals to all over the map.  Now many complain about our map being too huge.  My concept is to make portal books craftable by mages.  To various locations including higher end dungeons at the upper levels.  These books would take many things to craft and make them an item mages could sell to warriors or even crafters wanting to get to a gathering source safetly.  

https://docs.google.com/spreadsheets/d/1rpE4JnJ2iiTBpUrLBfibWOsYIWgSmgLmx1tTrBf25DY/edit?usp=sharing 

This is my initial concept in rough form.  The recipes have yet to be finialized.  These would be created using a quill at a desk (thinking the  old desk graphic (id 550 and 551)

**Comment by Brightrim** [comment]
New issue that includes portal book crafting as part of spatial magic: https://github.com/Illarion-eV/Illarion-Content/issues/310

It is already implemented and functioning on the magic test server, should anyone be interested in giving it a look.
