### ISSUE TITLE
Ropes lack a description.

### ISSUE THREAD

**Issue by EviePryler** [Illarion-eV/Illarion-Content#153]
All static and hand tools now have descriptions on their lookat.  Ropes were missed. Item  2760

**Comment by estralis** [comment]
When you have a text, I can add it to the database. A rope is not a hand tool but it never hurts to have a description. I see the tying code is still active, I am not sure we want to keep it.

**Comment by estralis** [comment]
English Version: A long length of braided threads, tightly woven together to form a strong aid when climbing  translated:  Ein langes Stück verflochtener Schnüre, zusammengewebt um eine stabile Hilfe beim Klettern zu sein.

**Comment by estralis** [comment]
I've modifed the German text: Ein langes Stück verflochtener Schnüre, zu einer stabilen Kletterhilfe zusammengeknüpft.
Rationale: Hilfe beim Klettern -> Kletterhilfe (less complex wording)
zusammengewebt -> zusammgeknüpft (ropes are not "gewebt")

Applied to both servers, issue closed.
