### ISSUE TITLE
Magical Blacksmith Item Lists Not Consistent

### ISSUE THREAD

**Issue by Quirkily** [Illarion-eV/Illarion-Content#157]
There is no consistency as to what order the gem lists are in when looking at them and trying to combine gems. Some start with Limited and increase in strength. Others start with Unique and decrease in strength. Yet others begin in the middle.

Ideally, this should be organized so they are all the same. Preferably starting with Limited and increasing in strength. But whatever is decided, all gem types should have the same list order.

**Example:**
Marrianne Forgeron (Galmair)...
emerald - limited to unique
ruby - unique to limited
obsidian - average to unique (a mess really)
sapphire - limited to unique
amethyst - limited to unique
topaz - unique to limited

Pheritaleth (Cadomyr) - same as Marrianne
Nizar (Runewick) - same as Marrianne

**Comment by estralis** [comment]
Fixed by https://github.com/Illarion-eV/Illarion-Server/pull/60
