### ISSUE TITLE
id_1206_claypit.lua buggy

### ISSUE THREAD

**Issue by EviePryler** [Illarion-eV/Illarion-Content#159]
The script id_1206_claypit.lua has a couple of bugs reguarding special clay holes.  The first is the lookat the the holes is not working.  The special description is not seen in the client.  The second is if you use a special hole and climb down it with a rope, the inform tells you that you need a rope.

**Comment by estralis** [comment]
Fixed by https://github.com/Illarion-eV/Illarion-Content/pull/244
