### ISSUE TITLE
Noobia - NPC Henry Cunnigan

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#168]
Harbour Master - Initial contact for new player.

Key tasks:
Adaptation of NPC Henry Cunnigan 
Inclusion of Noobia quest line

Proposal:
Welcome and set scene (tavern / harbour / market).
Quest - Speak to an NPC.
Provide torch and advise more can be purchased in the harbour market.
Quest - Equip torch.
Quest - Use torch.
Send to meet Nimbur Goldbrew.

Dependent on:
Map revision - Stage 1
Noobia - Inline tutorial 
Noobia - NPC revision
Noobia - Quest line

**Comment by slightlycomatose** [comment]
Include check of NPC appearance - incorporate 'leather bound journal' as item 2604 in hand.

**Comment by slightlycomatose** [comment]
Translation completed by @Capswickk

**Comment by slightlycomatose** [comment]
Available for preliminary testing in conjunction with Tutorial I (partially completed).
Set quest status for 309 to 1 pending triggerfield and database changes.

**Comment by Capswick** [comment]
Tested. Didn't find any issues.

**Comment by slightlycomatose** [comment]
Final quest ID 330 incorporated - testing to run from triggerfield initiation.
Proof read by @Ealaine
