### ISSUE TITLE
Noobia - NPC Nimbur Goldbrew

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#169]
Brewer - Introduction to fighting / gathering / crafting.

Key tasks:
Adaptation of NPC Nimbur Goldhand 
Inclusion of Noobia quest line

Proposal:
Greet and introduce the microbrewery and tavern.
Introduce brewing as a craft.
Warn about rats stealing apples from the orchard and provide a club in case any are seen.
Quest - Pick some apples from the orchard.
+ Kill a rat spawned in the orchard.
Provide other ingredients and a spoon for brewing.
Quest - Brew a bottle of cider.
Send to meet Viola Baywillow.

Dependent on:
Map revision - Stage 1
Noobia - Inline tutorial
Noobia - NPC revision
Noobia - Quest line

**Comment by slightlycomatose** [comment]
Include check of NPC appearance - Replace hammer with beer mug (item 1909) and spoon (item 227) in hand. Graphics currently don't show but have in place for any change to functionality.

**Comment by slightlycomatose** [comment]
Re-position to ensure name not covered by microbrewery structure. Await confirmation of spacing for inline components.

**Comment by slightlycomatose** [comment]
Translation completed by @Capswickk

**Comment by slightlycomatose** [comment]
Available for preliminary testing in conjunction with Tutorial II (partially completed).
Set quest status for 313 to 1 pending triggerfield and database changes.

**Comment by Capswick** [comment]
Name still obstructed, works fine otherwise

**Comment by slightlycomatose** [comment]
Relocated to 710 297 0 with expansion of tutorial area.

**Comment by slightlycomatose** [comment]
Final quest ID 331 incorporated - testing to run from triggerfield initiation.
Proof read by @Ealaine
