### ISSUE TITLE
Noobia - NPC Viola Baywillow

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#170]
Realm tutor - Informant for realm selection.

Key tasks:
Adaptation of NPC Viola Baywillow 
Inclusion of Noobia quest line

Proposal:
Greet and introduce the realms.
Options for extended information about realms.
Open-ended options for realm selection and exploring tavern / market.
Transfer quests from NPC Hummi Olaficht to provide further links to realms. 

Dependent on:
Map revision - Stage 1
Noobia - Inline tutorial
Noobia NPC revision
Noobia - Quest line

**Comment by slightlycomatose** [comment]
With @Capswikk for translation.

**Comment by Capswickk** [comment]
Translation completed!

**Comment by slightlycomatose** [comment]
Local functionality, including quests relocated from Hummi Olaficht, confirmed.
Full testing to follow incorporation with Noobia@Troll'sHaven.

**Comment by slightlycomatose** [comment]
Include check of NPC appearance - Replace staff with book (item 106).

**Comment by slightlycomatose** [comment]
Functionality / DE check by Aly

**Comment by slightlycomatose** [comment]
EN check by TiaSarah

**Comment by Capswick** [comment]
Functionality check DE/EN on a local test server, no issues.
