### ISSUE TITLE
Rework gathering speed calculation

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#173]
Adjust gathering speed calculation to crafting speed calculation.

**Comment by slightlycomatose** [comment]
Checked at skill 0, 50, and 100. Gathering speed seems reasonable. It feels quite rapid at skill 100 but that should not present an issue with no enhancement possible and limited resources.

**Comment by estralis** [comment]
If you are happy with the implementation, could you please set the issue to "reviewer approved"? We'll surely revisit the calculation at one point but for now, I think we have smoothed the edges.
