### ISSUE TITLE
Reduce chance for random events

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#174]

**Comment by slightlycomatose** [comment]
Significant reduction in random drops of low value items to make gathering a far 'cleaner' process.
Propose a review of these items at some point as some do not seem appropriate findings.
Rationalisation of higher value drops in conjunction with #184 to prepare for further development.
Fully functional with acceptable probabilities for current game conditions. 
Discrepancy in the map and shard probabilities comment but no impact on functionality.
