### ISSUE TITLE
Reduce wear on tools

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#181]
Rationale: 

About how long an item should last: The longest crafting action can take five minutes theoritcally with us not using the full range. But if we say a crafting action of five minutes should not take away 10 durability points (warning threshold), one durability point has to last at least 30 seconds. Now it is 18 seconds. So in total, a new tool has to last 50 minutes. With margin, we can set 60 minutes, so effectively doubling the time a tool lasts.

**Comment by slightlycomatose** [comment]
Significant increase in use from a single tool, giving a better feel to the game and in keeping with associated development.
