### ISSUE TITLE
Explorer Guild - Marker Stones

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#200]
Revision of marker stones as per proposal by @Brightrim to revamp the Explorer Guild, including new zoning and greater immersion. 

Production of marker stone list to include:
Stone location
Zone allocation
Immersive description 
Progress inform

**Comment by slightlycomatose** [comment]
Initial spreadsheet produced by @NeiaC
https://docs.google.com/spreadsheets/d/1U3K_HqLX3H6DUqjS-CQEtJUC1q_g0VruMBc01G3l6SU/edit#gid=0

Zones and stone distribution under review.

**Comment by brightrim** [comment]
Opening an issue for the first step we will take instead of this broader one. Moved relevant links and a link to this issue to the projects page for world realisation.
