### ISSUE TITLE
Prevent usage of broken weapons and armours

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#208]
The fighting system should treat broken weapons and armours as if they weren't there, not just reduce their effect to 0.

**Comment by Kerruan** [comment]
I'd have three questions for now related to the issue.

- Should the malus be still applied for broken shields?

> The malus for shields is also applied to broken ones.
> So current state:  broken shield + short sword  = 5% Parry chance
> Afterwards (ignoring the shield):   (shield) + short sword = 16% parry chance


- Should the char skill wrestling when both weapons/shields are broken? 

> Ignoring broken weapons would lead to skilling wrestling.
> Should it really skill wrestling or nothing?

- Or was the main idea to auto unequip weapons/armours which are broken during combat?

**Comment by dayjaby** [comment]
@estralis This can also be closed.
