### ISSUE TITLE
Suggestion for a change

### ISSUE THREAD

**Issue by LadyAly** [Illarion-eV/Illarion-Content#209]
Cadomyr NPC Hector_Valerion: makes me somehow... special, no?
In german is used wichtig better translate it to important instead of special ?
(He wants to be a important person for the queen. Not special as a person itself.)

**Comment by estralis** [comment]
Fixed by https://github.com/Illarion-eV/Illarion-Content/commit/966da152cfa6636073b6554afb55f49cafe8db53#diff-1579b7fb48b3bdb81d6e6d7f30b734c9
