### ISSUE TITLE
Typos NPC Tronruk

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#213]
Aly reports:
Cadomyr NPC Tronruk sagt: Durch verlorenes Gleichgeweicht Chief steckte ein mehr harte Schläge und verlor schlußendlich Kampf gegen Don. Orks waren geschockt und suchten nach blutiger Rache. = 
Gleichgewicht
NPC Tronruk sagt: Echse weiter angreifen wie auch Ommie mit namen Jefferson. Orks formen noch einmal und schlugen einen nach anderen bis fallen nach anderen - selbst in orkisch :smile: ist das zweite nach anderen wohl zuviel
NPC Tronruk sagt: Das war Tag von Grün Knurren! Mich stolz zu sein Ork! Erinnert glorreichen Tag. Und seit bereit für nächstes Ork Treffen! Chief Rugh'toh...Er grunzt, schließt seine Augen und wir leise. = wird ?

**Comment by vilarion** [comment]
"Und seit bereit für nächstes Ork Treffen" ... seid

**Comment by Kerruan** [comment]
Is this completely fixed by #221 ?

**Comment by slightlycomatose** [comment]
Due for removal with Troll's Haven development, so best not to invest further time.
