### ISSUE TITLE
Move tutorial NPCs to new locations

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#216]
703 290 0 Henry Cunnigan - West
706 297 0 Nimbur Goldbrew (formerly Goldhand) - West
693 292 0 Viola Baywillow - South

**Comment by slightlycomatose** [comment]
Position and orientation confirmed correct.
Potential to move Henry Cunnigan north with land extension should tutorial feel crowded.

**Comment by slightlycomatose** [comment]
Position of Nimbur Goldbrew revised to expand tutorial area.
710 297 0
