### ISSUE TITLE
Allow attribute trainers to change attributes beyond race limits

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#219]
It has been reported that the trainer NPCs cannot lower attributes that are above the race's limits. Expected behaviour would be that such attribute changes are possible, also raising an attribute that is below the race's limit. Of course, raising above or lower below the limit should not be possible.

**Comment by Brightrim** [comment]
In relation to issue #325 , the GM tool on dev can now make permanent changes to stats. Unlike the trainer that can only change the stat by the value of 1 each time, resulting in illegal values, GM tools can just directly put in a legal value for the stats all in one go before saving the changes, which should result in no further errors. Meanwhile to allow the trainers to do the same, they would either have to be allowed to change more than one value at a time or server changes are needed to account for this use case scenario. Given how this problem only occurs with older characters created before the new race stat value limits were determined, I think it is sufficient to leave it to GMs to deal with on a case by case basis given the new GM tool feature.
