### ISSUE TITLE
You can "steal" map bottled drinks.

### ISSUE THREAD

**Issue by KayMD** [Illarion-eV/Illarion-Content#228]
When you fill a cup with beer/wine from a bottle on the map, the bottle will go to your inventory when emptied. The "fixed" bottle will stay gone until the map is reloaded.

It should instead be swapped in place with an empty bottle for 1 rot cycle (or less). An alternative fix would be to just prevent interaction with these bottles, which I do not find preferable.

Here is where the bottle is going from a map item to an inventory item: [bottles.lua:141](https://github.com/Illarion-eV/Illarion-Content/blob/master/item/bottles.lua#L141)

**Comment by merung** [comment]
While the script is not really accessable for scripting beginners, KayMD pointed to the specific line were the issue is, and changing it to world:swap might be a good task for someone new to scripting for Illarion.

**Comment by EviePryler** [comment]
Are you talking about a bottle from a vendors stall say? If so there are two fixes i can think of to make it where we can't interact. Fast map hack : Put an invisible item on the bottles and they can then no longer be activated.  Second is to set up a special item data where they can not be used.  Thoughts?

**Comment by KayMD** [comment]
The bottle I stole was some wine in the Galmair bath area. Personally, I'd rather see them remain available for interactionjust with the script changed to swap it with an empty bottle and then some time later replace it again with the filled bottle.
