### ISSUE TITLE
We have a swarm of Enraged Akatults

### ISSUE THREAD

**Issue by KayMD** [Illarion-eV/Illarion-Content#233]
Something has gone awry with Akatult's spawn/phase change. Her chamber in that dungeon is now packed full of copies of herself, which occasionally escape into the main area with defensors where they can TPK whoever arrives. 

Example of there being a swarm: https://cdn.discordapp.com/attachments/744611800670011512/796421285445763082/unknown.png

**Comment by EviePryler** [comment]
I will change the enraged akaltut to revert to the original akaltut after a time frame (like the weakened liche). This will stop having many enraged as the akaltut is the boss and has a slow spawn time.

**Comment by KayMD** [comment]
I have gotten a clarification from the reporting player that the akatults were _not_ able to get out of their area, so it isn't a barrier issue

**Comment by slightlycomatose** [comment]
1142 should spawn Akaltut but currently spawns the eggs which hatch into an enraged Akaltut.
As the incorrect monster is present, the server is likely trying to spawn another and we are getting endless enraged Akaltuts.
Database and script look unchanged and issue not previously reported.

**Comment by estralis** [comment]
Issue confirmed - it is a mistake in the design. The server spawns a new "normal" Akaltut whenever there is no normal Akaltut around. So any enraged one does not count. This means we can get an endless amount of Akaltuts. A possible solution is to remove the spawn from the database and write a scheduled function that spawns a "normal" Akaltut in case no form of Akaltut is present (mage, spider, normal Akaltut, enraged). This needs to be tied into the function that hatches an Akaltut from an egg. Not a trivial fix but clearly necessary if the monster should be unique.

**Comment by estralis** [comment]
M;aybe it is even easier than I thought:
That enraged form spawns after some time by a scheduled function. The function could just check if there is already another Akaltut form (spider queen, mage, normal Akaltut) around. If there is one, no additional enraged Akaltut is spawned.
This would then "reset" the quest, though
So if the not enraged form respawns faster than the enraged form hatches, the players need to start over.
But this might be a simpler solution.

**Comment by Brightrim** [comment]
Pushed a fix for testing and added to the milestone for the next update
