### ISSUE TITLE
server.standardfighting: DropAmmo shows unexpected behaviour.

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#235]
"mozart" reports unexpected behaviour of the named function. Bug confirmed and reproduced.

**Comment by merung** [comment]
I remember we discussed such a thing before. How was it reproduced?

**Comment by estralis** [comment]
Fixed by https://github.com/Illarion-eV/Illarion-Content/commit/52444c47edc4dafe88f070b719f29a39703dc14f (typo in commit message).
