### ISSUE TITLE
Remove redundant trigger fields

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#284]
https://github.com/Illarion-eV/Illarion-Content/blob/develop/triggerfield/noobia_aldania.lua
https://github.com/Illarion-eV/Illarion-Content/blob/develop/triggerfield/noobia_groknar.lua
https://github.com/Illarion-eV/Illarion-Content/blob/develop/triggerfield/noobia_nargon.lua

**Comment by estralis** [comment]
All old tutorial triggerfields removed from database.
