### ISSUE TITLE
Undocumented quests

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#286]
Investigate on: 355,644,860,861,862

**Comment by estralis** [comment]
355: Two characters, both status 4
644: Eight characters, status 1+2
860, 861: Various characters, random numbers as status
862: Nine characters, status 1

**Comment by Brightrim** [comment]
Found:
quest 860 in item.id_2745_parchment.lua line 167
quest 861 in alchemy.teaching.transformation_dog.lua line 160
quest 862 in alchemy.teaching.transformation_dog.lua line 85
quest 644 in npc.ruzusss.npc line 76
no trace of quest 355 in the scripts

**Comment by estralis** [comment]
355: No method found how this status can be obtained. Existing status culled. ID free for use. Taken for Pathway.
644: quest.ruzusss_644_cadomyr, added to csv
860: Used in function "LearnLenniersDream", id_2745_parchment.lua, related to Alchemy. Added to csv.
861: Used in function "CorrectSightingPotion", transformation_dog.lua, related to Alchemy. Added to csv.
862: Used in function "ApperanceOfDog", transformation_dog.lua, related to Alchemy. Added to csv.

Thanks @Brightrim for your investigation!
