### ISSUE TITLE
Find replacement for triggerfield.noobia_explorer

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#290]
This will be a temporary solution until full revision of the Explorer Guild and associated marker stones is in place (#200).

**Comment by slightlycomatose** [comment]
Further adjustment required to avoid overlap with harbour trigger field when taken at speed. If we relocated the explorer stones in Troll's Haven it would be possible to give better spacing for the tutorial.

**Comment by slightlycomatose** [comment]
Marker stone relocated further along pier and database updated.
