### ISSUE TITLE
Reduce use of log()

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#326]
The script log gets flooded with too many messages that add little value to it. Some should be removed. @slightlycomatose to define which ones are superfluous.

Candidates:

- [Donation]
- [taxes]
- [gems]
- [tax switch] (few entries)
- Potions

**Comment by slightlycomatose** [comment]
[Donation] - Remove
[taxes] - Keep (ideally combine with gems to form a single entry)
[gems] - Keep (see above)
[tax switch] (few entries) - Keep
Potions - Remove (attribute potions only so incomplete)

**Comment by estralis** [comment]
Done locally, to be merged after next update. I did not merge taxes and gems as this would be much more work than the rest in total and I think we should revisit this once we change something about the tax/gems logics.
