### ISSUE TITLE
Add lacking german translations for the next update

### ISSUE THREAD

**Issue by Brightrim** [Illarion-eV/Illarion-Content#340]
Multiple issues in the august milestone have lacking german translations marked with "GERMAN TRANSLATION HERE", easily found by just doing a folder-wide search in VSC.

Additionally all the repair kits(items 4011-4065) require german names and descriptions in the database to match the english ones.

**Comment by estralis** [comment]
Can we split housing from this as it would require a separate commit to a different branch?

**Comment by Brightrim** [comment]
Housing separated into https://github.com/Illarion-eV/Illarion-Content/issues/341

**Comment by estralis** [comment]
Database also done.
