### ISSUE TITLE
Tracker of persistent tiles

### ISSUE THREAD

**Issue by brightrim** [Illarion-eV/Illarion-Content#346]
Due to the risk of random tiles being made persistent without documentation, which might disrupt map changes due to how persistent tiles override the underlying map, a tracker could be useful.

The functionality of the tracker would be part of the GM tools, ideally the one that already handles persistence.

To avoid lag, and accounting for how we might use more z layers than currently in the future, it would default to only scanning the z layer you are currently on. It would scan from x/y coordinates 0 to 1023, which are the current confines of the main map and should therefore also cover any tiles in any underground or above ground maps if not on z layer 0. Non default custom option would allow setting a range of layers and coordinates to scan.

Any script use of persistence should also be documented in this function so that it can separate GM-set/undocumented persistence and script-set persistence when it reports, ideally even referencing them by the name of their purpose for being persistent.

How to best list the coordinates given that the amount can be vast also needs to be looked into.

**Comment by Brightrim** [comment]
A version of this has been implemented. Needs a review by @slightlycomatose
