### ISSUE TITLE
InputDialog script error in housing

### ISSUE THREAD

**Issue by brightrim** [Illarion-eV/Illarion-Content#368]
Track down and solve the cause of
``1 Nov 19 16:24:16 Script (err): Exception in InputDialog callback: /usr/share/illarion/scripts/housing/utility.lua:1749: attempt to index field '?' (a nil value)``

**Comment by Brightrim** [comment]
Unable to replicate, utility script for extending rent appears to work fine. Some unique steps must be required to replicate this.

**Comment by brightrim** [comment]
With all the changes there have been in housing since then and how it has not appeared since, I am closing this.
