### ISSUE TITLE
ItemLookAt script error in housing

### ISSUE THREAD

**Issue by brightrim** [Illarion-eV/Illarion-Content#369]
Track down and solve the cause of 
``15 Nov 19 16:34:35 Script (err): Invalid return type in CraftingDialog callback: Expected type ItemLookAt``

**Comment by Brightrim** [comment]
Unable to replicate. Need more information on how this occurred to begin with.

**Comment by brightrim** [comment]
Has not happened since, closing this. Can always reopen if it occurs again one day, but potentially fixed by the myriad of changes that happened to the system since.
