### ISSUE TITLE
German translation for construction trowel description

### ISSUE THREAD

**Issue by Brightrim** [Illarion-eV/Illarion-Content#380]
Item ID 3918 aka the construction trowel used in housing has had its English description changed in the dev database as per feedback from @slightlycomatose . The German description needs to be amended accordingly.

Original German: Mit der Baukelle kannst du auf deinem Grundstück bauen und deine Umgebung gestalten.
Original English: Using the construction trowel on property land will allow you to build and customise your surroundings.
New English: Using the construction trowel  on property land where you have the tenant's permission will allow you to build and customise your surroundings.

**Comment by estralis** [comment]
Done, changed to
`Mit der Baukelle kannst du, solange du das Baurecht hast, auf einem Grundstück bauen und deine Umgebung gestalten.`
